import { useAddonRepo } from "./addon.repository";
import { useHelmService } from "../../services/helm.service";
import { useK8sService } from "../../services/k8s.service";
import {
  TAddon,
  TAddonInput,
  TAddonUpdateInput,
  TAddonType,
  TAddonStatus,
  TAddonConnectionInfo,
  ADDON_CATALOG,
  getAddonCatalogEntry,
  getAddonDefaultPort,
  isDatabaseType,
  isRedisType,
  schemaAddonUpdate,
} from "./addon.model";
import { BadRequestError, NotFoundError, InternalServerError, AppError } from "../../utils/error";
import { logger } from "../../utils";
import * as crypto from "crypto";
import { useDNSService } from "../../services/dns.service";

// =============================================================================
// Helpers
// =============================================================================

/**
 * Generate a secure random password
 */
function generatePassword(length: number = 24): string {
  return crypto.randomBytes(length).toString("base64").slice(0, length);
}

/**
 * Get nested value from object using dot notation key
 */
function getNestedValue(obj: Record<string, any>, key: string): any {
  return key.split(".").reduce((o, k) => o?.[k], obj);
}

/**
 * Set nested value in object using dot notation key
 */
function setNestedValue(obj: Record<string, any>, key: string, value: any): void {
  const keys = key.split(".");
  const lastKey = keys.pop()!;
  const target = keys.reduce((o, k) => {
    if (!o[k]) o[k] = {};
    return o[k];
  }, obj);
  target[lastKey] = value;
}

/**
 * Build Helm values from user config based on addon type.
 * Translates user-friendly config (replicas, tls, rootPassword, etc.) to Helm chart values.
 */
function buildHelmValues(
  type: TAddonType,
  config: Record<string, any>,
  baseValues: Record<string, any>
): { values: Record<string, any>; generatedPassword?: string } {
  const values = { ...baseValues };
  let generatedPassword: string | undefined;

  // Handle mongodb-replicaset type (uses nested mongodb key)
  if (type === "mongodb-replicaset") {
    // Ensure mongodb key exists
    if (!values.mongodb) {
      values.mongodb = {};
    }

    // Replicas
    if (config.replicas) {
      values.mongodb.replicaCount = Number(config.replicas);
    }

    // TLS
    if (config.tls === true) {
      values.mongodb.tls = { enabled: true, autoGenerated: true };
    }

    // Root password
    if (config.rootPassword) {
      values.mongodb.auth = { ...values.mongodb.auth, rootPassword: config.rootPassword };
    } else {
      generatedPassword = generatePassword();
      values.mongodb.auth = { ...values.mongodb.auth, rootPassword: generatedPassword };
    }

    // Application user
    if (config.createUser && config.username && config.password) {
      values.mongodb.auth = {
        ...values.mongodb.auth,
        usernames: [config.username],
        passwords: [config.password],
        databases: [config.database || config.username],
      };
    }

    // Storage size
    if (config.storageSize) {
      values.mongodb.persistence = { ...values.mongodb.persistence, size: config.storageSize };
    }

    // Resources
    if (config.resources) {
      values.mongodb.resources = config.resources;
    }

    // DNS configuration (MongoDB Atlas-style subdomain)
    if (config.dns?.enabled && config.dns?.baseDomain) {
      values.dns = {
        enabled: true,
        subdomain: config.dns.subdomain || "",  // Empty = use release name
        baseDomain: config.dns.baseDomain,
        replicaSetName: values.mongodb.replicaSetName || "rs0",
        tlsEnabled: config.tls === true,
      };
    }

    // S3 Backup configuration
    if (config.backup?.enabled && config.backup?.s3?.bucket) {
      values.backup = {
        enabled: true,
        schedule: config.backup.schedule || "0 2 * * *",
        retention: config.backup.retention || 7,
        s3: {
          bucket: config.backup.s3.bucket,
          endpoint: config.backup.s3.endpoint || "",
          region: config.backup.s3.region || "us-east-1",
          prefix: config.backup.s3.prefix || "mongodb-backups",
          accessKeyId: config.backup.s3.accessKeyId || "",
          secretAccessKey: config.backup.s3.secretAccessKey || "",
          existingSecret: config.backup.s3.existingSecret || "",
        },
      };
    }

    return { values, generatedPassword };
  }

  // Database types (MongoDB, PostgreSQL, MySQL, MariaDB, ClickHouse)
  if (isDatabaseType(type)) {
    // Replicas / Architecture
    if (config.replicas) {
      const replicas = Number(config.replicas);
      
      switch (type) {
        case "mongodb":
          if (replicas > 1) {
            values.architecture = "replicaset";
            values.replicaCount = replicas;
          } else {
            values.architecture = "standalone";
          }
          break;
        case "postgresql":
          if (replicas > 1) {
            values.architecture = "replication";
            values.readReplicas = { replicaCount: replicas - 1 };
          } else {
            values.architecture = "standalone";
          }
          break;
        case "mysql":
        case "mariadb":
          if (replicas > 1) {
            values.architecture = "replication";
            values.secondary = { replicaCount: replicas - 1 };
          } else {
            values.architecture = "standalone";
          }
          break;
        case "clickhouse":
          values.replicaCount = replicas;
          values.shards = 1;
          break;
      }
    }

    // TLS
    if (config.tls === true) {
      switch (type) {
        case "mongodb":
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "postgresql":
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "mysql":
        case "mariadb":
          values.auth = { ...values.auth, usePasswordFiles: true };
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "clickhouse":
          values.tls = { enabled: true };
          break;
      }
    }

    // Root password
    if (config.rootPassword) {
      switch (type) {
        case "mongodb":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "postgresql":
          values.auth = { ...values.auth, postgresPassword: config.rootPassword };
          break;
        case "mysql":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "mariadb":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "clickhouse":
          values.auth = { ...values.auth, password: config.rootPassword };
          break;
      }
    } else {
      // Generate password if not provided
      generatedPassword = generatePassword();
      switch (type) {
        case "mongodb":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "postgresql":
          values.auth = { ...values.auth, postgresPassword: generatedPassword };
          break;
        case "mysql":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "mariadb":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "clickhouse":
          values.auth = { ...values.auth, password: generatedPassword };
          break;
      }
    }

    // Application user (optional)
    if (config.createUser && config.username && config.password) {
      switch (type) {
        case "mongodb":
          values.auth = {
            ...values.auth,
            usernames: [config.username],
            passwords: [config.password],
            databases: [config.database || config.username],
          };
          break;
        case "postgresql":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
        case "mysql":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
        case "mariadb":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
      }
    }
  }

  // Redis-like types (Redis, KeyDB, Dragonfly)
  if (isRedisType(type)) {
    // Password
    if (config.redisPassword) {
      switch (type) {
        case "redis":
          values.auth = { ...values.auth, enabled: true, password: config.redisPassword };
          break;
        case "keydb":
          values.password = config.redisPassword;
          break;
        case "dragonfly":
          values.auth = { ...values.auth, enabled: true, password: config.redisPassword };
          break;
      }
    } else {
      // Generate password if not provided
      generatedPassword = generatePassword();
      switch (type) {
        case "redis":
          values.auth = { ...values.auth, enabled: true, password: generatedPassword };
          break;
        case "keydb":
          values.password = generatedPassword;
          break;
        case "dragonfly":
          values.auth = { ...values.auth, enabled: true, password: generatedPassword };
          break;
      }
    }

    // Cluster mode
    if (config.clusterMode === true) {
      const nodes = config.clusterNodes || 3;
      switch (type) {
        case "redis":
          values.architecture = "replication";
          values.replica = { replicaCount: nodes };
          values.sentinel = { enabled: true };
          break;
        case "keydb":
          values.nodes = nodes;
          values.multiMaster = true;
          break;
        case "dragonfly":
          values.replicaCount = nodes;
          break;
      }
    } else {
      switch (type) {
        case "redis":
          values.architecture = "standalone";
          break;
      }
    }
  }

  // Other specific addon configs
  switch (type) {
    case "elasticsearch":
      if (config.replicas) {
        values.master = { ...values.master, replicaCount: config.replicas };
        values.data = { ...values.data, replicaCount: config.replicas };
      }
      break;

    case "minio":
      if (config.rootPassword) {
        values.auth = { ...values.auth, rootPassword: config.rootPassword };
      } else if (!values.auth?.rootPassword) {
        generatedPassword = generatedPassword || generatePassword();
        values.auth = { ...values.auth, rootPassword: generatedPassword };
      }
      break;

    case "rabbitmq":
      if (config.password) {
        values.auth = { ...values.auth, password: config.password };
      } else if (!values.auth?.password) {
        generatedPassword = generatedPassword || generatePassword();
        values.auth = { ...values.auth, password: generatedPassword };
      }
      if (config.username) {
        values.auth = { ...values.auth, username: config.username };
      }
      break;

    case "grafana":
      if (config.adminPassword) {
        values.adminPassword = config.adminPassword;
      } else if (!values.adminPassword) {
        generatedPassword = generatedPassword || generatePassword();
        values.adminPassword = generatedPassword;
      }
      break;
  }

  return { values, generatedPassword };
}

/**
 * Extended connection info that includes DNS-based connection strings.
 */
export type TAddonConnectionInfoExtended = TAddonConnectionInfo & {
  srvConnectionString?: string;  // mongodb+srv:// connection string
  dnsClusterHost?: string;       // e.g., "mydb.db.example.com"
  backupEnabled?: boolean;
  backupSchedule?: string;
};

/**
 * Build connection info based on addon type, Helm values, and generated password.
 */
function buildConnectionInfo(
  addon: TAddon,
  generatedPassword?: string
): TAddonConnectionInfoExtended {
  const catalogEntry = getAddonCatalogEntry(addon.type);
  const template = catalogEntry.connectionTemplate;
  
  // Handle mongodb-replicaset specially (uses nested mongodb key)
  if (addon.type === "mongodb-replicaset") {
    const replicaCount = addon.values?.mongodb?.replicaCount || 3;
    const replicaSetName = addon.values?.mongodb?.replicaSetName || "rs0";
    const headlessService = addon.releaseName + "-mongodb-headless";
    
    // Build replica set hosts
    const hosts: string[] = [];
    for (let i = 0; i < replicaCount; i++) {
      hosts.push(addon.releaseName + "-mongodb-" + i + "." + headlessService + "." + addon.namespace + ".svc.cluster.local:27017");
    }
    
    const username = addon.config?.createUser && addon.config?.username
      ? addon.config.username
      : template?.defaultUsername || "root";
    
    const password = addon.config?.createUser && addon.config?.password
      ? addon.config.password
      : generatedPassword || getNestedValue(addon.values, template?.passwordKey || "mongodb.auth.rootPassword");
    
    const database = addon.config?.database || "admin";
    const tlsEnabled = addon.values?.mongodb?.tls?.enabled || false;
    const tlsParam = tlsEnabled ? "&tls=true" : "";
    
    const connectionInfo: TAddonConnectionInfoExtended = {
      host: hosts[0].split(":")[0],  // Primary host for display
      port: 27017,
      username,
      password,
      connectionString: "mongodb://" + username + ":" + password + "@" + hosts.join(",") + "/" + database + "?replicaSet=" + replicaSetName + tlsParam,
    };
    
    // Add DNS-based connection info if configured
    if (addon.values?.dns?.enabled && addon.values?.dns?.baseDomain) {
      const subdomain = addon.values.dns.subdomain || addon.releaseName;
      const clusterHost = subdomain + "." + addon.values.dns.baseDomain;
      connectionInfo.dnsClusterHost = clusterHost;
      connectionInfo.srvConnectionString = "mongodb+srv://" + username + ":" + password + "@" + clusterHost + "/" + database + "?authSource=admin";
    }
    
    // Add backup info
    if (addon.values?.backup?.enabled) {
      connectionInfo.backupEnabled = true;
      connectionInfo.backupSchedule = addon.values.backup.schedule;
    }
    
    return connectionInfo;
  }
  
  // Build internal K8s DNS hostname
  // For master/primary services, some charts use different naming
  let serviceSuffix = "";
  if (addon.type === "mongodb" && addon.values?.architecture === "replicaset") {
    serviceSuffix = "-headless";
  } else if (addon.type === "postgresql" && addon.values?.architecture === "replication") {
    serviceSuffix = "-primary";
  } else if (["mysql", "mariadb"].includes(addon.type) && addon.values?.architecture === "replication") {
    serviceSuffix = "-primary";
  } else if (addon.type === "redis" && addon.values?.architecture === "replication") {
    serviceSuffix = "-master";
  }
  
  const host = `${addon.releaseName}${serviceSuffix}.${addon.namespace}.svc.cluster.local`;
  const port = template?.portOverride || catalogEntry.defaultPort;

  const connectionInfo: TAddonConnectionInfo = {
    host,
    port,
  };

  // Extract username
  if (template?.defaultUsername) {
    connectionInfo.username = template.defaultUsername;
  }
  if (template?.usernameKey) {
    const username = getNestedValue(addon.values, template.usernameKey);
    if (username) {
      connectionInfo.username = username;
    }
  }
  // Override with app user if created
  if (addon.config?.createUser && addon.config?.username) {
    connectionInfo.username = addon.config.username;
  }

  // Extract password
  if (generatedPassword) {
    connectionInfo.password = generatedPassword;
  } else if (template?.passwordKey) {
    const password = getNestedValue(addon.values, template.passwordKey);
    if (password) {
      connectionInfo.password = password;
    }
  }
  // Override with app user password if created
  if (addon.config?.createUser && addon.config?.password) {
    connectionInfo.password = addon.config.password;
  }

  // Build connection string based on type
  connectionInfo.connectionString = buildConnectionString(addon.type, connectionInfo, addon.config);

  return connectionInfo;
}

/**
 * Build a connection string for the given addon type.
 */
function buildConnectionString(
  type: TAddonType,
  info: TAddonConnectionInfo,
  config?: Record<string, any>
): string {
  const auth = info.username && info.password
    ? `${encodeURIComponent(info.username)}:${encodeURIComponent(info.password)}@`
    : info.password
    ? `:${encodeURIComponent(info.password)}@`
    : "";

  switch (type) {
    case "mongodb": {
      const db = config?.database || "admin";
      return `mongodb://${auth}${info.host}:${info.port}/${db}`;
    }
    case "postgresql": {
      const db = config?.database || "postgres";
      return `postgresql://${auth}${info.host}:${info.port}/${db}`;
    }
    case "mysql":
    case "mariadb": {
      const db = config?.database || "";
      return `mysql://${auth}${info.host}:${info.port}/${db}`;
    }
    case "redis":
    case "keydb":
    case "dragonfly": {
      return info.password
        ? `redis://:${encodeURIComponent(info.password)}@${info.host}:${info.port}`
        : `redis://${info.host}:${info.port}`;
    }
    case "rabbitmq": {
      return `amqp://${auth}${info.host}:${info.port}`;
    }
    case "elasticsearch":
    case "meilisearch":
    case "typesense":
      return `http://${info.host}:${info.port}`;
    case "minio":
      return `http://${info.host}:${info.port}`;
    case "kafka":
      return `${info.host}:${info.port}`;
    case "nats":
      return `nats://${info.host}:${info.port}`;
    default:
      return `http://${info.host}:${info.port}`;
  }
}

// =============================================================================
// Addon Service
// =============================================================================

export function useAddonService() {
  const repo = useAddonRepo();
  const helm = useHelmService();

  /**
   * Create a new addon and deploy it via Helm.
   */
  async function create(data: TAddonInput): Promise<{ addonId: string; message: string }> {
    // Check Helm availability
    if (!helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot deploy addons.");
    }

    // Check for existing addon with same name
    const existing = await repo.getByName(data.name, data.organizationId);
    if (existing) {
      throw new BadRequestError(`Addon with name "${data.name}" already exists.`);
    }

    // Create addon record
    const addonId = await repo.add(data);
    const addon = await repo.getById(addonId);
    if (!addon) {
      throw new InternalServerError("Failed to retrieve created addon.");
    }

    // Start async deployment
    deployAddon(addon).catch((error) => {
      logger.log({
        level: "error",
        message: `[Addon] Failed to deploy addon ${addonId}: ${error.message}`,
      });
    });

    return {
      addonId,
      message: `Addon "${addon.name}" created. Deployment in progress.`,
    };
  }

  /**
   * Deploy an addon via Helm (internal async function).
   */
  async function deployAddon(addon: TAddon): Promise<void> {
    const addonId = addon._id!.toString();

    try {
      // Update status to deploying
      await repo.updateStatus(addonId, "deploying");

      const catalogEntry = getAddonCatalogEntry(addon.type);
      const chart = catalogEntry.chart;
      const version = addon.version || catalogEntry.version;

      // Build Helm values from user config
      const { values, generatedPassword } = buildHelmValues(
        addon.type,
        addon.config || {},
        addon.values
      );

      // Add required repos for non-bitnami charts
      await ensureHelmRepo(chart);

      // Install via Helm
      await helm.install(
        addon.releaseName,
        chart,
        addon.namespace,
        values,
        {
          version,
          createNamespace: true,
          wait: true,
          timeout: "15m",
        }
      );

      // Update addon with connection info and running status
      const connectionInfo = buildConnectionInfo(addon, generatedPassword);
      await repo.updateConnectionInfo(addonId, connectionInfo);
      await repo.updateById(addonId, { values }); // Store final values
      await repo.updateStatus(addonId, "running");

      logger.log({
        level: "info",
        message: `[Addon] Successfully deployed addon ${addon.name} (${addon.type})`,
      });
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(addonId, "failed", errorMessage);
      logger.log({
        level: "error",
        message: `[Addon] Failed to deploy addon ${addon.name}: ${errorMessage}`,
      });

      // Re-throw for caller if needed
      if (error instanceof AppError) throw error;
      throw new InternalServerError(`Failed to deploy addon: ${errorMessage}`);
    }
  }

  /**
   * Ensure the Helm repo is added for a chart.
   */
  async function ensureHelmRepo(chart: string): Promise<void> {
    const [repoName] = chart.split("/");
    
    const repoUrls: Record<string, string> = {
      bitnami: "https://charts.bitnami.com/bitnami",
      grafana: "https://grafana.github.io/helm-charts",
      prometheus: "https://prometheus-community.github.io/helm-charts",
      "prometheus-community": "https://prometheus-community.github.io/helm-charts",
      meilisearch: "https://meilisearch.github.io/meilisearch-kubernetes",
      nats: "https://nats-io.github.io/k8s/helm/charts/",
      minio: "https://charts.min.io/",
      gitea: "https://dl.gitea.io/charts/",
      gitlab: "https://charts.gitlab.io/",
      temporal: "https://go.temporal.io/helm-charts",
      posthog: "https://posthog.github.io/charts-clickhouse/",
      enapter: "https://enapter.github.io/charts/",
      dragonflydb: "https://dragonflydb.github.io/dragonfly-operator/",
    };

    const repoUrl = repoUrls[repoName];
    if (repoUrl) {
      try {
        await helm.addRepo(repoName, repoUrl);
      } catch (error: any) {
        // Ignore "already exists" errors
        if (!error.message?.includes("already exists")) {
          logger.log({
            level: "warn",
            message: `[Addon] Failed to add Helm repo ${repoName}: ${error.message}`,
          });
        }
      }
    }
  }

  /**
   * Update an addon (triggers Helm upgrade).
   */
  async function update(
    id: string,
    data: TAddonUpdateInput
  ): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Validate update data
    const { error, value } = schemaAddonUpdate.validate(data, { stripUnknown: true });
    if (error) {
      throw new BadRequestError(error.message);
    }

    // Check Helm availability for value/version updates
    const needsHelmUpgrade = value.values || value.version || value.config;
    if (needsHelmUpgrade && !helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot update addon.");
    }

    // Check for name conflicts
    if (value.name && value.name !== addon.name) {
      const existing = await repo.getByName(value.name, addon.organizationId?.toString());
      if (existing && existing._id?.toString() !== id) {
        throw new BadRequestError(`Addon with name "${value.name}" already exists.`);
      }
    }

    // Prepare updated values
    const updatedConfig = value.config
      ? { ...addon.config, ...value.config }
      : addon.config;
    const updatedValues = value.values
      ? { ...addon.values, ...value.values }
      : addon.values;
    const updatedVersion = value.version || addon.version;

    // Update the record first
    await repo.updateById(id, {
      ...(value.name && { name: value.name }),
      ...(value.values && { values: updatedValues }),
      ...(value.version && { version: updatedVersion }),
      ...(value.config && { config: updatedConfig }),
    });

    // Trigger Helm upgrade if needed
    if (needsHelmUpgrade) {
      await repo.updateStatus(id, "deploying");

      // Run upgrade async
      upgradeAddon({ ...addon, config: updatedConfig }, updatedValues, updatedVersion).catch((error) => {
        logger.log({
          level: "error",
          message: `[Addon] Failed to upgrade addon ${id}: ${error.message}`,
        });
      });

      return {
        message: `Addon "${addon.name}" update in progress.`,
      };
    }

    return {
      message: `Addon "${addon.name}" updated.`,
    };
  }

  /**
   * Upgrade an addon via Helm (internal async function).
   */
  async function upgradeAddon(
    addon: TAddon,
    baseValues: Record<string, any>,
    version: string
  ): Promise<void> {
    const addonId = addon._id!.toString();

    try {
      const catalogEntry = getAddonCatalogEntry(addon.type);
      const chart = catalogEntry.chart;

      // Build Helm values from config
      const { values, generatedPassword } = buildHelmValues(
        addon.type,
        addon.config || {},
        baseValues
      );

      await helm.upgrade(
        addon.releaseName,
        chart,
        addon.namespace,
        values,
        {
          version,
          wait: true,
          timeout: "15m",
        }
      );

      // Update connection info if password was regenerated
      if (generatedPassword) {
        const connectionInfo = buildConnectionInfo(addon, generatedPassword);
        await repo.updateConnectionInfo(addonId, connectionInfo);
      }

      await repo.updateStatus(addonId, "running");

      logger.log({
        level: "info",
        message: `[Addon] Successfully upgraded addon ${addon.name}`,
      });
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(addonId, "failed", errorMessage);
      logger.log({
        level: "error",
        message: `[Addon] Failed to upgrade addon ${addon.name}: ${errorMessage}`,
      });
    }
  }

  /**
   * Delete an addon and uninstall the Helm release.
   */
  async function remove(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Update status to deleting
    await repo.updateStatus(id, "deleting");

    try {
      // Uninstall Helm release
      if (helm.isAvailable()) {
        await helm.uninstall(addon.releaseName, addon.namespace);
      }

      // Delete from database
      await repo.deleteById(id);

      logger.log({
        level: "info",
        message: `[Addon] Deleted addon ${addon.name}`,
      });

      return {
        message: `Addon "${addon.name}" deleted.`,
      };
    } catch (error: any) {
      // If Helm uninstall fails, still try to delete from DB
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.log({
        level: "warn",
        message: `[Addon] Helm uninstall failed for ${addon.name}, proceeding with DB deletion: ${errorMessage}`,
      });

      await repo.deleteById(id);

      return {
        message: `Addon "${addon.name}" deleted (Helm uninstall may have failed).`,
      };
    }
  }

  /**
   * Get connection info for an addon (sensitive operation).
   */
  async function getConnectionInfo(id: string): Promise<TAddonConnectionInfo | null> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (!addon.connectionInfo) {
      return null;
    }

    return addon.connectionInfo;
  }

  /**
   * Start a stopped addon.
   */
  async function start(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.status === "running") {
      return { message: "Addon is already running." };
    }

    // For now, we re-deploy to start
    // In the future, could scale replicas from 0 to N
    await repo.updateStatus(id, "deploying");

    deployAddon(addon).catch((error) => {
      logger.log({
        level: "error",
        message: `[Addon] Failed to start addon ${id}: ${error.message}`,
      });
    });

    return { message: `Starting addon "${addon.name}"...` };
  }

  /**
   * Stop a running addon (scales to 0).
   */
  async function stop(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.status === "stopped") {
      return { message: "Addon is already stopped." };
    }

    // Scale to 0 replicas
    const catalogEntry = getAddonCatalogEntry(addon.type);
    const values = {
      ...addon.values,
      replicaCount: 0,
    };

    try {
      await helm.upgrade(
        addon.releaseName,
        catalogEntry.chart,
        addon.namespace,
        values,
        { wait: true, timeout: "5m" }
      );

      await repo.updateStatus(id, "stopped");
      return { message: `Addon "${addon.name}" stopped.` };
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.log({
        level: "error",
        message: `[Addon] Failed to stop addon ${addon.name}: ${errorMessage}`,
      });
      throw new InternalServerError(`Failed to stop addon: ${errorMessage}`);
    }
  }

  /**
   * Restart a running addon.
   */
  async function restart(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    await repo.updateStatus(id, "deploying");

    // Re-deploy with same values
    const catalogEntry = getAddonCatalogEntry(addon.type);
    
    try {
      await helm.upgrade(
        addon.releaseName,
        catalogEntry.chart,
        addon.namespace,
        addon.values,
        { wait: true, timeout: "10m" }
      );

      await repo.updateStatus(id, "running");
      return { message: `Addon "${addon.name}" restarted.` };
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(id, "failed", errorMessage);
      throw new InternalServerError(`Failed to restart addon: ${errorMessage}`);
    }
  }

  /**
   * Refresh addon status by checking Helm release status.
   */
  async function refreshStatus(id: string): Promise<{ status: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (!helm.isAvailable()) {
      return { status: addon.status };
    }

    try {
      const releaseStatus = await helm.status(addon.releaseName, addon.namespace);

      if (!releaseStatus) {
        // Release not found — mark as failed if it was supposed to be running
        if (addon.status === "running") {
          await repo.updateStatus(id, "failed", "Helm release not found");
        }
        return { status: "failed" };
      }

      // Map Helm status to addon status
      let newStatus = addon.status;
      switch (releaseStatus.status) {
        case "deployed":
          newStatus = "running";
          break;
        case "pending-install":
        case "pending-upgrade":
        case "pending-rollback":
          newStatus = "deploying";
          break;
        case "failed":
          newStatus = "failed";
          break;
        case "uninstalling":
          newStatus = "deleting";
          break;
      }

      if (newStatus !== addon.status) {
        await repo.updateStatus(id, newStatus as TAddonStatus);
      }

      return { status: newStatus };
    } catch (error: any) {
      logger.log({
        level: "warn",
        message: `[Addon] Failed to refresh status for ${addon.name}: ${error.message}`,
      });
      return { status: addon.status };
    }
  }

  /**
   * Get the addon catalog (available types and their info).
   */
  function getCatalog() {
    return Object.entries(ADDON_CATALOG).map(([type, info]) => ({
      type,
      chart: info.chart,
      version: info.version,
      defaultPort: info.defaultPort,
    }));
  }

  /**
   * Sync addon status with Helm for all deployed addons.
   * Used by scheduled tasks.
   */
  async function syncAllStatuses(): Promise<{ synced: number; errors: number }> {
    let synced = 0;
    let errors = 0;

    const addons = await repo.getByStatus("running");
    addons.push(...(await repo.getByStatus("deploying")));

    for (const addon of addons) {
      try {
        await refreshStatus(addon._id!.toString());
        synced++;
      } catch (error) {
        errors++;
      }
    }

    return { synced, errors };
  }

  /**
   * Scale an addon (update replica count).
   * Only valid for database types and certain other addons.
   */
  async function scale(id: string, replicas: number): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Validate replicas
    if (replicas < 1 || replicas > 7) {
      throw new BadRequestError("Replicas must be between 1 and 7.");
    }

    // Only certain types can be scaled
    const scalableTypes: TAddonType[] = [
      "mongodb", "postgresql", "mysql", "mariadb", "clickhouse",
      "redis", "keydb", "dragonfly",
      "elasticsearch",
    ];

    if (!scalableTypes.includes(addon.type)) {
      throw new BadRequestError(`Addon type "${addon.type}" does not support scaling.`);
    }

    // Check Helm availability
    if (!helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot scale addon.");
    }

    // Update config with new replica count
    const newConfig = { ...addon.config, replicas };

    // Update the record
    await repo.updateById(id, { config: newConfig });
    await repo.updateStatus(id, "deploying");

    // Rebuild Helm values with new config
    const catalogEntry = getAddonCatalogEntry(addon.type);
    const { values } = buildHelmValues(addon.type, newConfig, addon.values);

    // Run upgrade async
    (async () => {
      try {
        await helm.upgrade(
          addon.releaseName,
          catalogEntry.chart,
          addon.namespace,
          values,
          {
            version: addon.version,
            wait: true,
            timeout: "15m",
          }
        );

        await repo.updateById(id, { values });
        await repo.updateStatus(id, "running");

        logger.log({
          level: "info",
          message: `[Addon] Scaled addon ${addon.name} to ${replicas} replicas`,
        });
      } catch (error: any) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        await repo.updateStatus(id, "failed", errorMessage);
        logger.log({
          level: "error",
          message: `[Addon] Failed to scale addon ${addon.name}: ${errorMessage}`,
        });
      }
    })();

    return { message: `Scaling addon "${addon.name}" to ${replicas} replicas...` };
  }

  /**
   * Get logs for an addon's pods
   */
  async function getLogs(
    id: string,
    options: { tailLines?: number; sinceSeconds?: number } = {}
  ): Promise<{ logs: string[] }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const k8s = useK8sService();

    // Get pods with label selector matching the Helm release
    const pods = await k8s.list(
      "v1",
      "Pod",
      addon.namespace,
      `app.kubernetes.io/instance=${addon.releaseName}`
    );

    const logs: string[] = [];
    for (const pod of pods) {
      try {
        const podLogs = await k8s.getPodLogs(pod.metadata.name, addon.namespace, {
          tailLines: options.tailLines || 100,
          sinceSeconds: options.sinceSeconds,
        });
        logs.push(`=== ${pod.metadata.name} ===\n${podLogs}`);
      } catch (error: any) {
        logs.push(`=== ${pod.metadata.name} ===\n[Error fetching logs: ${error.message}]`);
      }
    }

    return { logs };
  }

  /**
   * Get Kubernetes events for an addon
   */
  async function getEvents(id: string): Promise<{ events: any[] }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const k8s = useK8sService();

    // Get events in the addon's namespace related to this release
    const allEvents = await k8s.getEvents(addon.namespace);

    // Filter to events mentioning the release name
    const relevantEvents = allEvents.filter(
      (event: any) =>
        event.involvedObject?.name?.includes(addon.releaseName) ||
        event.metadata?.name?.includes(addon.releaseName)
    );

    // Format events for response
    const events = relevantEvents.map((event: any) => ({
      type: event.type,
      reason: event.reason,
      message: event.message,
      firstTimestamp: event.firstTimestamp,
      lastTimestamp: event.lastTimestamp,
      count: event.count,
      involvedObject: {
        kind: event.involvedObject?.kind,
        name: event.involvedObject?.name,
      },
    }));

    // Sort by last timestamp descending
    events.sort(
      (a, b) =>
        new Date(b.lastTimestamp || 0).getTime() -
        new Date(a.lastTimestamp || 0).getTime()
    );

    return { events };
  }

  // -------------------------------------------------------------------------
  // DNS Configuration (MongoDB Atlas-style subdomain)
  // -------------------------------------------------------------------------

  /**
   * Configure DNS for a mongodb-replicaset addon.
   * Creates SRV and A records for mongodb+srv:// connection strings.
   */
  async function configureDNS(
    id: string,
    options: { subdomain?: string } = {}
  ): Promise<{ message: string; clusterHost?: string; srvConnectionString?: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.type !== "mongodb-replicaset") {
      throw new BadRequestError("DNS configuration is only available for mongodb-replicaset type.");
    }

    const dns = useDNSService();

    const dnsConfig = await dns.getDBConfig();
    if (!dnsConfig) {
      throw new BadRequestError(
        "DNS is not configured. Please configure DNS settings in Settings > DNS."
      );
    }

    // External access must be enabled — pod IPs are internal and not internet-routable
    const externalAccessEnabled = addon.values?.mongodb?.externalAccess?.enabled;
    if (!externalAccessEnabled) {
      throw new BadRequestError(
        "External access must be enabled before configuring DNS. " +
        "Re-deploy or update this addon with externalAccess.enabled=true " +
        "(NodePort or LoadBalancer). Then retry DNS configuration."
      );
    }

    const replicaCount = addon.values?.mongodb?.replicaCount || 3;
    const replicaSetName = addon.values?.mongodb?.replicaSetName || "rs0";
    const subdomain = options.subdomain || addon.values?.dns?.subdomain || addon.name;
    const serviceType: string = addon.values?.mongodb?.externalAccess?.service?.type || "NodePort";

    const k8s = useK8sService();
    const nodes: Array<{ host: string; port: number }> = [];

    if (serviceType === "LoadBalancer") {
      // Each replica gets its own LoadBalancer service: {releaseName}-mongodb-{i}-external
      for (let i = 0; i < replicaCount; i++) {
        const svcName = `${addon.releaseName}-mongodb-${i}-external`;
        const svc = await k8s.getService(addon.namespace, svcName);
        const ingress = svc?.status?.loadBalancer?.ingress;
        if (ingress?.[0]?.ip) {
          nodes.push({ host: ingress[0].ip, port: 27017 });
        } else if (ingress?.[0]?.hostname) {
          // Some LB providers (AWS) give a hostname rather than an IP.
          // DNS SRV needs an IP for A records; log and skip hostname-only ingress.
          logger.log({
            level: "warn",
            message: `[Addon] LoadBalancer for ${svcName} exposes a hostname, not an IP — cannot create A record.`,
          });
        }
      }
    } else {
      // NodePort: all replicas share node IPs but use different node ports.
      // Get the external IP from the first available K8s node.
      const k8sNodes = await k8s.getNodes();
      const nodeIPs: string[] = [];
      for (const n of k8sNodes) {
        const addresses: Array<{ type: string; address: string }> = (n as any).status?.addresses || [];
        const external = addresses.find((a) => a.type === "ExternalIP")?.address;
        const internal = addresses.find((a) => a.type === "InternalIP")?.address;
        const ip = external || internal;
        if (ip) nodeIPs.push(ip);
      }

      for (let i = 0; i < replicaCount; i++) {
        const svcName = `${addon.releaseName}-mongodb-${i}-external`;
        const svc = await k8s.getService(addon.namespace, svcName);
        const nodePort: number = (svc as any)?.spec?.ports?.[0]?.nodePort || 27017;
        // Prefer the i-th node's IP if available (pods may be on different nodes),
        // fall back to the first node IP for single-node clusters (K3s).
        const ip = nodeIPs[i] ?? nodeIPs[0];
        if (ip) {
          nodes.push({ host: ip, port: nodePort });
        }
      }
    }

    if (nodes.length === 0) {
      throw new BadRequestError(
        "Could not determine MongoDB node IPs from K8s Services. " +
        "Ensure the replica set is running and externalAccess services are ready."
      );
    }

    // Get root password for connection string
    const password = addon.connectionInfo?.password ||
      getNestedValue(addon.values, "mongodb.auth.rootPassword") ||
      "";

    // Create DNS records via Cloudflare
    const result = await dns.setupReplicaSet({
      databaseName: subdomain,
      nodes,
      adminUser: "root",
      adminPassword: password,
      replicaSetName,
    });

    if (!result) {
      throw new InternalServerError("DNS setup returned no result.");
    }

    // Persist DNS config back onto the addon
    await repo.updateById(id, {
      values: {
        ...addon.values,
        dns: {
          enabled: true,
          subdomain,
          baseDomain: dnsConfig.baseDomain,
          clusterHost: result.clusterHost,
          nodeHosts: result.nodeHosts,
          srvConnectionString: result.srvConnectionString,
          records: result.records,
        },
      },
      connectionInfo: {
        ...addon.connectionInfo,
        srvConnectionString: result.srvConnectionString,
        dnsClusterHost: result.clusterHost,
      } as any,
    });

    logger.log({
      level: "info",
      message: `[Addon] DNS configured for ${addon.name}: ${result.clusterHost}`,
    });

    return {
      message: "DNS configured successfully.",
      clusterHost: result.clusterHost,
      srvConnectionString: result.srvConnectionString,
    };
  }

  /**
   * Remove DNS configuration for an addon.
   */
  async function removeDNS(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const dnsConfig = addon.values?.dns;
    if (!dnsConfig?.enabled || !dnsConfig?.records?.length) {
      return { message: "DNS not configured for this addon." };
    }

    // Teardown records
    const dns = useDNSService();
    await dns.teardown(dnsConfig.records);

    // Update addon to remove DNS config
    await repo.updateById(id, {
      values: {
        ...addon.values,
        dns: { enabled: false },
      },
      connectionInfo: {
        ...addon.connectionInfo,
        srvConnectionString: undefined,
        dnsClusterHost: undefined,
      } as any,
    });

    logger.log({
      level: "info",
      message: "[Addon] DNS removed for " + addon.name,
    });

    return { message: "DNS configuration removed." };
  }

  // -------------------------------------------------------------------------
  // Backup Operations
  // -------------------------------------------------------------------------

  /**
   * Configure S3 backup for a mongodb-replicaset addon.
   */
  async function configureBackup(
    id: string,
    config: {
      enabled: boolean;
      schedule?: string;
      retention?: number;
      s3: {
        bucket: string;
        endpoint?: string;
        region?: string;
        prefix?: string;
        accessKeyId: string;
        secretAccessKey: string;
      };
    }
  ): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.type !== "mongodb-replicaset") {
      throw new BadRequestError("Backup configuration is only available for mongodb-replicaset type.");
    }

    // Update addon config
    const updatedConfig = {
      ...addon.config,
      backup: config,
    };

    // Update Helm values
    const updatedValues = {
      ...addon.values,
      backup: {
        enabled: config.enabled,
        schedule: config.schedule || "0 2 * * *",
        retention: config.retention || 7,
        s3: {
          bucket: config.s3.bucket,
          endpoint: config.s3.endpoint || "",
          region: config.s3.region || "us-east-1",
          prefix: config.s3.prefix || "mongodb-backups",
          accessKeyId: config.s3.accessKeyId,
          secretAccessKey: config.s3.secretAccessKey,
        },
      },
    };

    await repo.updateById(id, {
      config: updatedConfig,
      values: updatedValues,
    });

    // Upgrade Helm release with new backup config
    if (addon.status === "running") {
      const catalogEntry = getAddonCatalogEntry(addon.type);
      try {
        await helm.upgrade(
          addon.releaseName,
          catalogEntry.chart,
          addon.namespace,
          updatedValues,
          { wait: true, timeout: "5m" }
        );
        logger.log({
          level: "info",
          message: "[Addon] Backup configured for " + addon.name,
        });
      } catch (err: any) {
        logger.log({
          level: "error",
          message: "[Addon] Failed to apply backup config: " + err.message,
        });
        throw new InternalServerError("Failed to apply backup configuration: " + err.message);
      }
    }

    return {
      message: config.enabled
        ? "Backup configured. Schedule: " + (config.schedule || "0 2 * * *")
        : "Backup disabled.",
    };
  }

  /**
   * Trigger an on-demand backup for a mongodb-replicaset addon.
   */
  async function triggerBackup(id: string): Promise<{ message: string; jobName?: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.type !== "mongodb-replicaset") {
      throw new BadRequestError("Backup is only available for mongodb-replicaset type.");
    }

    if (!addon.values?.backup?.enabled) {
      throw new BadRequestError(
        "Backup is not configured. Configure backup settings first."
      );
    }

    // Create a Job from the CronJob
    const k8s = useK8sService();
    const cronJobName = addon.releaseName + "-backup";
    const jobName = cronJobName + "-manual-" + Date.now();

    try {
      // Get the CronJob spec
      const cronJob = await k8s.getCronJob(addon.namespace, cronJobName);
      if (!cronJob) {
        throw new NotFoundError("Backup CronJob not found. Ensure backup is configured.");
      }

      // Create a Job from the CronJob template
      await k8s.createJobFromCronJob(addon.namespace, cronJobName, jobName);

      logger.log({
        level: "info",
        message: "[Addon] Manual backup triggered for " + addon.name + ": " + jobName,
      });

      return {
        message: "Backup job started.",
        jobName,
      };
    } catch (err: any) {
      logger.log({
        level: "error",
        message: "[Addon] Failed to trigger backup: " + err.message,
      });
      throw new InternalServerError("Failed to trigger backup: " + err.message);
    }
  }

  /**
   * List backup jobs for an addon.
   */
  async function listBackups(id: string): Promise<{
    backups: Array<{
      name: string;
      status: string;
      startTime?: Date;
      completionTime?: Date;
    }>;
  }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const k8s = useK8sService();
    const jobs = await k8s.listJobs(addon.namespace, {
      labelSelector: "app.kubernetes.io/instance=" + addon.releaseName + ",app.kubernetes.io/component=backup",
    });

    const backups = jobs.map((job: any) => ({
      name: job.metadata?.name || "unknown",
      status: job.status?.succeeded ? "completed" : job.status?.failed ? "failed" : "running",
      startTime: job.status?.startTime ? new Date(job.status.startTime) : undefined,
      completionTime: job.status?.completionTime ? new Date(job.status.completionTime) : undefined,
    }));

    return { backups };
  }

  return {
    create,
    update,
    remove,
    start,
    stop,
    restart,
    scale,
    getConnectionInfo,
    refreshStatus,
    getCatalog,
    syncAllStatuses,
    getLogs,
    getEvents,
    // DNS operations
    configureDNS,
    removeDNS,
    // Backup operations
    configureBackup,
    triggerBackup,
    listBackups,
  };
}
