import { useAddonRepo } from "./addon.repository";
import { useHelmService } from "../../services/helm.service";
import { useK8sService } from "../../services/k8s.service";
import {
  TAddon,
  TAddonInput,
  TAddonUpdateInput,
  TAddonType,
  TAddonStatus,
  TAddonConnectionInfo,
  ADDON_CATALOG,
  getAddonCatalogEntry,
  getAddonDefaultPort,
  isDatabaseType,
  isRedisType,
  schemaAddonUpdate,
} from "./addon.model";
import { BadRequestError, NotFoundError, InternalServerError, AppError } from "../../utils/error";
import { logger } from "../../utils";
import * as crypto from "crypto";

// =============================================================================
// Helpers
// =============================================================================

/**
 * Generate a secure random password
 */
function generatePassword(length: number = 24): string {
  return crypto.randomBytes(length).toString("base64").slice(0, length);
}

/**
 * Get nested value from object using dot notation key
 */
function getNestedValue(obj: Record<string, any>, key: string): any {
  return key.split(".").reduce((o, k) => o?.[k], obj);
}

/**
 * Set nested value in object using dot notation key
 */
function setNestedValue(obj: Record<string, any>, key: string, value: any): void {
  const keys = key.split(".");
  const lastKey = keys.pop()!;
  const target = keys.reduce((o, k) => {
    if (!o[k]) o[k] = {};
    return o[k];
  }, obj);
  target[lastKey] = value;
}

/**
 * Build Helm values from user config based on addon type.
 * Translates user-friendly config (replicas, tls, rootPassword, etc.) to Helm chart values.
 */
function buildHelmValues(
  type: TAddonType,
  config: Record<string, any>,
  baseValues: Record<string, any>
): { values: Record<string, any>; generatedPassword?: string } {
  const values = { ...baseValues };
  let generatedPassword: string | undefined;

  // Database types (MongoDB, PostgreSQL, MySQL, MariaDB, ClickHouse)
  if (isDatabaseType(type)) {
    // Replicas / Architecture
    if (config.replicas) {
      const replicas = Number(config.replicas);
      
      switch (type) {
        case "mongodb":
          if (replicas > 1) {
            values.architecture = "replicaset";
            values.replicaCount = replicas;
          } else {
            values.architecture = "standalone";
          }
          break;
        case "postgresql":
          if (replicas > 1) {
            values.architecture = "replication";
            values.readReplicas = { replicaCount: replicas - 1 };
          } else {
            values.architecture = "standalone";
          }
          break;
        case "mysql":
        case "mariadb":
          if (replicas > 1) {
            values.architecture = "replication";
            values.secondary = { replicaCount: replicas - 1 };
          } else {
            values.architecture = "standalone";
          }
          break;
        case "clickhouse":
          values.replicaCount = replicas;
          values.shards = 1;
          break;
      }
    }

    // TLS
    if (config.tls === true) {
      switch (type) {
        case "mongodb":
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "postgresql":
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "mysql":
        case "mariadb":
          values.auth = { ...values.auth, usePasswordFiles: true };
          values.tls = { enabled: true, autoGenerated: true };
          break;
        case "clickhouse":
          values.tls = { enabled: true };
          break;
      }
    }

    // Root password
    if (config.rootPassword) {
      switch (type) {
        case "mongodb":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "postgresql":
          values.auth = { ...values.auth, postgresPassword: config.rootPassword };
          break;
        case "mysql":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "mariadb":
          values.auth = { ...values.auth, rootPassword: config.rootPassword };
          break;
        case "clickhouse":
          values.auth = { ...values.auth, password: config.rootPassword };
          break;
      }
    } else {
      // Generate password if not provided
      generatedPassword = generatePassword();
      switch (type) {
        case "mongodb":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "postgresql":
          values.auth = { ...values.auth, postgresPassword: generatedPassword };
          break;
        case "mysql":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "mariadb":
          values.auth = { ...values.auth, rootPassword: generatedPassword };
          break;
        case "clickhouse":
          values.auth = { ...values.auth, password: generatedPassword };
          break;
      }
    }

    // Application user (optional)
    if (config.createUser && config.username && config.password) {
      switch (type) {
        case "mongodb":
          values.auth = {
            ...values.auth,
            usernames: [config.username],
            passwords: [config.password],
            databases: [config.database || config.username],
          };
          break;
        case "postgresql":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
        case "mysql":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
        case "mariadb":
          values.auth = {
            ...values.auth,
            username: config.username,
            password: config.password,
            database: config.database || config.username,
          };
          break;
      }
    }
  }

  // Redis-like types (Redis, KeyDB, Dragonfly)
  if (isRedisType(type)) {
    // Password
    if (config.redisPassword) {
      switch (type) {
        case "redis":
          values.auth = { ...values.auth, enabled: true, password: config.redisPassword };
          break;
        case "keydb":
          values.password = config.redisPassword;
          break;
        case "dragonfly":
          values.auth = { ...values.auth, enabled: true, password: config.redisPassword };
          break;
      }
    } else {
      // Generate password if not provided
      generatedPassword = generatePassword();
      switch (type) {
        case "redis":
          values.auth = { ...values.auth, enabled: true, password: generatedPassword };
          break;
        case "keydb":
          values.password = generatedPassword;
          break;
        case "dragonfly":
          values.auth = { ...values.auth, enabled: true, password: generatedPassword };
          break;
      }
    }

    // Cluster mode
    if (config.clusterMode === true) {
      const nodes = config.clusterNodes || 3;
      switch (type) {
        case "redis":
          values.architecture = "replication";
          values.replica = { replicaCount: nodes };
          values.sentinel = { enabled: true };
          break;
        case "keydb":
          values.nodes = nodes;
          values.multiMaster = true;
          break;
        case "dragonfly":
          values.replicaCount = nodes;
          break;
      }
    } else {
      switch (type) {
        case "redis":
          values.architecture = "standalone";
          break;
      }
    }
  }

  // Other specific addon configs
  switch (type) {
    case "elasticsearch":
      if (config.replicas) {
        values.master = { ...values.master, replicaCount: config.replicas };
        values.data = { ...values.data, replicaCount: config.replicas };
      }
      break;

    case "minio":
      if (config.rootPassword) {
        values.auth = { ...values.auth, rootPassword: config.rootPassword };
      } else if (!values.auth?.rootPassword) {
        generatedPassword = generatedPassword || generatePassword();
        values.auth = { ...values.auth, rootPassword: generatedPassword };
      }
      break;

    case "rabbitmq":
      if (config.password) {
        values.auth = { ...values.auth, password: config.password };
      } else if (!values.auth?.password) {
        generatedPassword = generatedPassword || generatePassword();
        values.auth = { ...values.auth, password: generatedPassword };
      }
      if (config.username) {
        values.auth = { ...values.auth, username: config.username };
      }
      break;

    case "grafana":
      if (config.adminPassword) {
        values.adminPassword = config.adminPassword;
      } else if (!values.adminPassword) {
        generatedPassword = generatedPassword || generatePassword();
        values.adminPassword = generatedPassword;
      }
      break;
  }

  return { values, generatedPassword };
}

/**
 * Build connection info based on addon type, Helm values, and generated password.
 */
function buildConnectionInfo(
  addon: TAddon,
  generatedPassword?: string
): TAddonConnectionInfo {
  const catalogEntry = getAddonCatalogEntry(addon.type);
  const template = catalogEntry.connectionTemplate;
  
  // Build internal K8s DNS hostname
  // For master/primary services, some charts use different naming
  let serviceSuffix = "";
  if (addon.type === "mongodb" && addon.values?.architecture === "replicaset") {
    serviceSuffix = "-headless";
  } else if (addon.type === "postgresql" && addon.values?.architecture === "replication") {
    serviceSuffix = "-primary";
  } else if (["mysql", "mariadb"].includes(addon.type) && addon.values?.architecture === "replication") {
    serviceSuffix = "-primary";
  } else if (addon.type === "redis" && addon.values?.architecture === "replication") {
    serviceSuffix = "-master";
  }
  
  const host = `${addon.releaseName}${serviceSuffix}.${addon.namespace}.svc.cluster.local`;
  const port = template?.portOverride || catalogEntry.defaultPort;

  const connectionInfo: TAddonConnectionInfo = {
    host,
    port,
  };

  // Extract username
  if (template?.defaultUsername) {
    connectionInfo.username = template.defaultUsername;
  }
  if (template?.usernameKey) {
    const username = getNestedValue(addon.values, template.usernameKey);
    if (username) {
      connectionInfo.username = username;
    }
  }
  // Override with app user if created
  if (addon.config?.createUser && addon.config?.username) {
    connectionInfo.username = addon.config.username;
  }

  // Extract password
  if (generatedPassword) {
    connectionInfo.password = generatedPassword;
  } else if (template?.passwordKey) {
    const password = getNestedValue(addon.values, template.passwordKey);
    if (password) {
      connectionInfo.password = password;
    }
  }
  // Override with app user password if created
  if (addon.config?.createUser && addon.config?.password) {
    connectionInfo.password = addon.config.password;
  }

  // Build connection string based on type
  connectionInfo.connectionString = buildConnectionString(addon.type, connectionInfo, addon.config);

  return connectionInfo;
}

/**
 * Build a connection string for the given addon type.
 */
function buildConnectionString(
  type: TAddonType,
  info: TAddonConnectionInfo,
  config?: Record<string, any>
): string {
  const auth = info.username && info.password
    ? `${encodeURIComponent(info.username)}:${encodeURIComponent(info.password)}@`
    : info.password
    ? `:${encodeURIComponent(info.password)}@`
    : "";

  switch (type) {
    case "mongodb": {
      const db = config?.database || "admin";
      return `mongodb://${auth}${info.host}:${info.port}/${db}`;
    }
    case "postgresql": {
      const db = config?.database || "postgres";
      return `postgresql://${auth}${info.host}:${info.port}/${db}`;
    }
    case "mysql":
    case "mariadb": {
      const db = config?.database || "";
      return `mysql://${auth}${info.host}:${info.port}/${db}`;
    }
    case "redis":
    case "keydb":
    case "dragonfly": {
      return info.password
        ? `redis://:${encodeURIComponent(info.password)}@${info.host}:${info.port}`
        : `redis://${info.host}:${info.port}`;
    }
    case "rabbitmq": {
      return `amqp://${auth}${info.host}:${info.port}`;
    }
    case "elasticsearch":
    case "meilisearch":
    case "typesense":
      return `http://${info.host}:${info.port}`;
    case "minio":
      return `http://${info.host}:${info.port}`;
    case "kafka":
      return `${info.host}:${info.port}`;
    case "nats":
      return `nats://${info.host}:${info.port}`;
    default:
      return `http://${info.host}:${info.port}`;
  }
}

// =============================================================================
// Addon Service
// =============================================================================

export function useAddonService() {
  const repo = useAddonRepo();
  const helm = useHelmService();

  /**
   * Create a new addon and deploy it via Helm.
   */
  async function create(data: TAddonInput): Promise<{ addonId: string; message: string }> {
    // Check Helm availability
    if (!helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot deploy addons.");
    }

    // Check for existing addon with same name
    const existing = await repo.getByName(data.name, data.organizationId);
    if (existing) {
      throw new BadRequestError(`Addon with name "${data.name}" already exists.`);
    }

    // Create addon record
    const addonId = await repo.add(data);
    const addon = await repo.getById(addonId);
    if (!addon) {
      throw new InternalServerError("Failed to retrieve created addon.");
    }

    // Start async deployment
    deployAddon(addon).catch((error) => {
      logger.log({
        level: "error",
        message: `[Addon] Failed to deploy addon ${addonId}: ${error.message}`,
      });
    });

    return {
      addonId,
      message: `Addon "${addon.name}" created. Deployment in progress.`,
    };
  }

  /**
   * Deploy an addon via Helm (internal async function).
   */
  async function deployAddon(addon: TAddon): Promise<void> {
    const addonId = addon._id!.toString();

    try {
      // Update status to deploying
      await repo.updateStatus(addonId, "deploying");

      const catalogEntry = getAddonCatalogEntry(addon.type);
      const chart = catalogEntry.chart;
      const version = addon.version || catalogEntry.version;

      // Build Helm values from user config
      const { values, generatedPassword } = buildHelmValues(
        addon.type,
        addon.config || {},
        addon.values
      );

      // Add required repos for non-bitnami charts
      await ensureHelmRepo(chart);

      // Install via Helm
      await helm.install(
        addon.releaseName,
        chart,
        addon.namespace,
        values,
        {
          version,
          createNamespace: true,
          wait: true,
          timeout: "15m",
        }
      );

      // Update addon with connection info and running status
      const connectionInfo = buildConnectionInfo(addon, generatedPassword);
      await repo.updateConnectionInfo(addonId, connectionInfo);
      await repo.updateById(addonId, { values }); // Store final values
      await repo.updateStatus(addonId, "running");

      logger.log({
        level: "info",
        message: `[Addon] Successfully deployed addon ${addon.name} (${addon.type})`,
      });
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(addonId, "failed", errorMessage);
      logger.log({
        level: "error",
        message: `[Addon] Failed to deploy addon ${addon.name}: ${errorMessage}`,
      });

      // Re-throw for caller if needed
      if (error instanceof AppError) throw error;
      throw new InternalServerError(`Failed to deploy addon: ${errorMessage}`);
    }
  }

  /**
   * Ensure the Helm repo is added for a chart.
   */
  async function ensureHelmRepo(chart: string): Promise<void> {
    const [repoName] = chart.split("/");
    
    const repoUrls: Record<string, string> = {
      bitnami: "https://charts.bitnami.com/bitnami",
      grafana: "https://grafana.github.io/helm-charts",
      prometheus: "https://prometheus-community.github.io/helm-charts",
      "prometheus-community": "https://prometheus-community.github.io/helm-charts",
      meilisearch: "https://meilisearch.github.io/meilisearch-kubernetes",
      nats: "https://nats-io.github.io/k8s/helm/charts/",
      minio: "https://charts.min.io/",
      gitea: "https://dl.gitea.io/charts/",
      gitlab: "https://charts.gitlab.io/",
      temporal: "https://go.temporal.io/helm-charts",
      posthog: "https://posthog.github.io/charts-clickhouse/",
      enapter: "https://enapter.github.io/charts/",
      dragonflydb: "https://dragonflydb.github.io/dragonfly-operator/",
    };

    const repoUrl = repoUrls[repoName];
    if (repoUrl) {
      try {
        await helm.addRepo(repoName, repoUrl);
      } catch (error: any) {
        // Ignore "already exists" errors
        if (!error.message?.includes("already exists")) {
          logger.log({
            level: "warn",
            message: `[Addon] Failed to add Helm repo ${repoName}: ${error.message}`,
          });
        }
      }
    }
  }

  /**
   * Update an addon (triggers Helm upgrade).
   */
  async function update(
    id: string,
    data: TAddonUpdateInput
  ): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Validate update data
    const { error, value } = schemaAddonUpdate.validate(data, { stripUnknown: true });
    if (error) {
      throw new BadRequestError(error.message);
    }

    // Check Helm availability for value/version updates
    const needsHelmUpgrade = value.values || value.version || value.config;
    if (needsHelmUpgrade && !helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot update addon.");
    }

    // Check for name conflicts
    if (value.name && value.name !== addon.name) {
      const existing = await repo.getByName(value.name, addon.organizationId?.toString());
      if (existing && existing._id?.toString() !== id) {
        throw new BadRequestError(`Addon with name "${value.name}" already exists.`);
      }
    }

    // Prepare updated values
    const updatedConfig = value.config
      ? { ...addon.config, ...value.config }
      : addon.config;
    const updatedValues = value.values
      ? { ...addon.values, ...value.values }
      : addon.values;
    const updatedVersion = value.version || addon.version;

    // Update the record first
    await repo.updateById(id, {
      ...(value.name && { name: value.name }),
      ...(value.values && { values: updatedValues }),
      ...(value.version && { version: updatedVersion }),
      ...(value.config && { config: updatedConfig }),
    });

    // Trigger Helm upgrade if needed
    if (needsHelmUpgrade) {
      await repo.updateStatus(id, "deploying");

      // Run upgrade async
      upgradeAddon({ ...addon, config: updatedConfig }, updatedValues, updatedVersion).catch((error) => {
        logger.log({
          level: "error",
          message: `[Addon] Failed to upgrade addon ${id}: ${error.message}`,
        });
      });

      return {
        message: `Addon "${addon.name}" update in progress.`,
      };
    }

    return {
      message: `Addon "${addon.name}" updated.`,
    };
  }

  /**
   * Upgrade an addon via Helm (internal async function).
   */
  async function upgradeAddon(
    addon: TAddon,
    baseValues: Record<string, any>,
    version: string
  ): Promise<void> {
    const addonId = addon._id!.toString();

    try {
      const catalogEntry = getAddonCatalogEntry(addon.type);
      const chart = catalogEntry.chart;

      // Build Helm values from config
      const { values, generatedPassword } = buildHelmValues(
        addon.type,
        addon.config || {},
        baseValues
      );

      await helm.upgrade(
        addon.releaseName,
        chart,
        addon.namespace,
        values,
        {
          version,
          wait: true,
          timeout: "15m",
        }
      );

      // Update connection info if password was regenerated
      if (generatedPassword) {
        const connectionInfo = buildConnectionInfo(addon, generatedPassword);
        await repo.updateConnectionInfo(addonId, connectionInfo);
      }

      await repo.updateStatus(addonId, "running");

      logger.log({
        level: "info",
        message: `[Addon] Successfully upgraded addon ${addon.name}`,
      });
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(addonId, "failed", errorMessage);
      logger.log({
        level: "error",
        message: `[Addon] Failed to upgrade addon ${addon.name}: ${errorMessage}`,
      });
    }
  }

  /**
   * Delete an addon and uninstall the Helm release.
   */
  async function remove(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Update status to deleting
    await repo.updateStatus(id, "deleting");

    try {
      // Uninstall Helm release
      if (helm.isAvailable()) {
        await helm.uninstall(addon.releaseName, addon.namespace);
      }

      // Delete from database
      await repo.deleteById(id);

      logger.log({
        level: "info",
        message: `[Addon] Deleted addon ${addon.name}`,
      });

      return {
        message: `Addon "${addon.name}" deleted.`,
      };
    } catch (error: any) {
      // If Helm uninstall fails, still try to delete from DB
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.log({
        level: "warn",
        message: `[Addon] Helm uninstall failed for ${addon.name}, proceeding with DB deletion: ${errorMessage}`,
      });

      await repo.deleteById(id);

      return {
        message: `Addon "${addon.name}" deleted (Helm uninstall may have failed).`,
      };
    }
  }

  /**
   * Get connection info for an addon (sensitive operation).
   */
  async function getConnectionInfo(id: string): Promise<TAddonConnectionInfo | null> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (!addon.connectionInfo) {
      return null;
    }

    return addon.connectionInfo;
  }

  /**
   * Start a stopped addon.
   */
  async function start(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.status === "running") {
      return { message: "Addon is already running." };
    }

    // For now, we re-deploy to start
    // In the future, could scale replicas from 0 to N
    await repo.updateStatus(id, "deploying");

    deployAddon(addon).catch((error) => {
      logger.log({
        level: "error",
        message: `[Addon] Failed to start addon ${id}: ${error.message}`,
      });
    });

    return { message: `Starting addon "${addon.name}"...` };
  }

  /**
   * Stop a running addon (scales to 0).
   */
  async function stop(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (addon.status === "stopped") {
      return { message: "Addon is already stopped." };
    }

    // Scale to 0 replicas
    const catalogEntry = getAddonCatalogEntry(addon.type);
    const values = {
      ...addon.values,
      replicaCount: 0,
    };

    try {
      await helm.upgrade(
        addon.releaseName,
        catalogEntry.chart,
        addon.namespace,
        values,
        { wait: true, timeout: "5m" }
      );

      await repo.updateStatus(id, "stopped");
      return { message: `Addon "${addon.name}" stopped.` };
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.log({
        level: "error",
        message: `[Addon] Failed to stop addon ${addon.name}: ${errorMessage}`,
      });
      throw new InternalServerError(`Failed to stop addon: ${errorMessage}`);
    }
  }

  /**
   * Restart a running addon.
   */
  async function restart(id: string): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    await repo.updateStatus(id, "deploying");

    // Re-deploy with same values
    const catalogEntry = getAddonCatalogEntry(addon.type);
    
    try {
      await helm.upgrade(
        addon.releaseName,
        catalogEntry.chart,
        addon.namespace,
        addon.values,
        { wait: true, timeout: "10m" }
      );

      await repo.updateStatus(id, "running");
      return { message: `Addon "${addon.name}" restarted.` };
    } catch (error: any) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      await repo.updateStatus(id, "failed", errorMessage);
      throw new InternalServerError(`Failed to restart addon: ${errorMessage}`);
    }
  }

  /**
   * Refresh addon status by checking Helm release status.
   */
  async function refreshStatus(id: string): Promise<{ status: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    if (!helm.isAvailable()) {
      return { status: addon.status };
    }

    try {
      const releaseStatus = await helm.status(addon.releaseName, addon.namespace);

      if (!releaseStatus) {
        // Release not found — mark as failed if it was supposed to be running
        if (addon.status === "running") {
          await repo.updateStatus(id, "failed", "Helm release not found");
        }
        return { status: "failed" };
      }

      // Map Helm status to addon status
      let newStatus = addon.status;
      switch (releaseStatus.status) {
        case "deployed":
          newStatus = "running";
          break;
        case "pending-install":
        case "pending-upgrade":
        case "pending-rollback":
          newStatus = "deploying";
          break;
        case "failed":
          newStatus = "failed";
          break;
        case "uninstalling":
          newStatus = "deleting";
          break;
      }

      if (newStatus !== addon.status) {
        await repo.updateStatus(id, newStatus as TAddonStatus);
      }

      return { status: newStatus };
    } catch (error: any) {
      logger.log({
        level: "warn",
        message: `[Addon] Failed to refresh status for ${addon.name}: ${error.message}`,
      });
      return { status: addon.status };
    }
  }

  /**
   * Get the addon catalog (available types and their info).
   */
  function getCatalog() {
    return Object.entries(ADDON_CATALOG).map(([type, info]) => ({
      type,
      chart: info.chart,
      version: info.version,
      defaultPort: info.defaultPort,
    }));
  }

  /**
   * Sync addon status with Helm for all deployed addons.
   * Used by scheduled tasks.
   */
  async function syncAllStatuses(): Promise<{ synced: number; errors: number }> {
    let synced = 0;
    let errors = 0;

    const addons = await repo.getByStatus("running");
    addons.push(...(await repo.getByStatus("deploying")));

    for (const addon of addons) {
      try {
        await refreshStatus(addon._id!.toString());
        synced++;
      } catch (error) {
        errors++;
      }
    }

    return { synced, errors };
  }

  /**
   * Scale an addon (update replica count).
   * Only valid for database types and certain other addons.
   */
  async function scale(id: string, replicas: number): Promise<{ message: string }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    // Validate replicas
    if (replicas < 1 || replicas > 7) {
      throw new BadRequestError("Replicas must be between 1 and 7.");
    }

    // Only certain types can be scaled
    const scalableTypes: TAddonType[] = [
      "mongodb", "postgresql", "mysql", "mariadb", "clickhouse",
      "redis", "keydb", "dragonfly",
      "elasticsearch",
    ];

    if (!scalableTypes.includes(addon.type)) {
      throw new BadRequestError(`Addon type "${addon.type}" does not support scaling.`);
    }

    // Check Helm availability
    if (!helm.isAvailable()) {
      throw new InternalServerError("Helm is not available. Cannot scale addon.");
    }

    // Update config with new replica count
    const newConfig = { ...addon.config, replicas };

    // Update the record
    await repo.updateById(id, { config: newConfig });
    await repo.updateStatus(id, "deploying");

    // Rebuild Helm values with new config
    const catalogEntry = getAddonCatalogEntry(addon.type);
    const { values } = buildHelmValues(addon.type, newConfig, addon.values);

    // Run upgrade async
    (async () => {
      try {
        await helm.upgrade(
          addon.releaseName,
          catalogEntry.chart,
          addon.namespace,
          values,
          {
            version: addon.version,
            wait: true,
            timeout: "15m",
          }
        );

        await repo.updateById(id, { values });
        await repo.updateStatus(id, "running");

        logger.log({
          level: "info",
          message: `[Addon] Scaled addon ${addon.name} to ${replicas} replicas`,
        });
      } catch (error: any) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        await repo.updateStatus(id, "failed", errorMessage);
        logger.log({
          level: "error",
          message: `[Addon] Failed to scale addon ${addon.name}: ${errorMessage}`,
        });
      }
    })();

    return { message: `Scaling addon "${addon.name}" to ${replicas} replicas...` };
  }

  /**
   * Get logs for an addon's pods
   */
  async function getLogs(
    id: string,
    options: { tailLines?: number; sinceSeconds?: number } = {}
  ): Promise<{ logs: string[] }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const k8s = useK8sService();

    // Get pods with label selector matching the Helm release
    const pods = await k8s.list(
      "v1",
      "Pod",
      addon.namespace,
      `app.kubernetes.io/instance=${addon.releaseName}`
    );

    const logs: string[] = [];
    for (const pod of pods) {
      try {
        const podLogs = await k8s.getPodLogs(pod.metadata.name, addon.namespace, {
          tailLines: options.tailLines || 100,
          sinceSeconds: options.sinceSeconds,
        });
        logs.push(`=== ${pod.metadata.name} ===\n${podLogs}`);
      } catch (error: any) {
        logs.push(`=== ${pod.metadata.name} ===\n[Error fetching logs: ${error.message}]`);
      }
    }

    return { logs };
  }

  /**
   * Get Kubernetes events for an addon
   */
  async function getEvents(id: string): Promise<{ events: any[] }> {
    const addon = await repo.getById(id);
    if (!addon) {
      throw new NotFoundError("Addon not found.");
    }

    const k8s = useK8sService();

    // Get events in the addon's namespace related to this release
    const allEvents = await k8s.getEvents(addon.namespace);

    // Filter to events mentioning the release name
    const relevantEvents = allEvents.filter(
      (event: any) =>
        event.involvedObject?.name?.includes(addon.releaseName) ||
        event.metadata?.name?.includes(addon.releaseName)
    );

    // Format events for response
    const events = relevantEvents.map((event: any) => ({
      type: event.type,
      reason: event.reason,
      message: event.message,
      firstTimestamp: event.firstTimestamp,
      lastTimestamp: event.lastTimestamp,
      count: event.count,
      involvedObject: {
        kind: event.involvedObject?.kind,
        name: event.involvedObject?.name,
      },
    }));

    // Sort by last timestamp descending
    events.sort(
      (a, b) =>
        new Date(b.lastTimestamp || 0).getTime() -
        new Date(a.lastTimestamp || 0).getTime()
    );

    return { events };
  }

  return {
    create,
    update,
    remove,
    start,
    stop,
    restart,
    scale,
    getConnectionInfo,
    refreshStatus,
    getCatalog,
    syncAllStatuses,
    getLogs,
    getEvents,
  };
}
